#### Metode i primjena vjestacke inteligencije
#### Laboratorijska vjezba 1
#### Student: Masovic Haris
#### Index: 1689/17993

## 3. Klasifikacija rukom pisanih cifri

### 3.1 Ucitavanje podataka

In [57]:
import keras
from keras.datasets import mnist

# py3 notebook

# ukljuciti za full prikaz podataka
# np.set_printoptions(threshold=np.inf)

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

#### train set
print('-- Train set')
print('')
print(*['Oblik seta podataka train_images je formata (n, px, px):', train_images.shape])
print('Prva vrijednost predstavlja broj slika u skupu, dok druga i treca vrijednost predstavljaju rezoluciju.')
print('')

## train labels

print(*['Velicina skupa train_labels:', len(train_labels)])
print('Sami prikaz train_labels skupa (pogledati threshold comment):')
print(train_labels)
print("")

## info - train_images

print(*['Element train_images type:', train_images.dtype])
print(*['Svaki element np niza kojim su kodirane slike zauzima:', train_images.itemsize, "byte"])
print(*['Citav skup u memoriji zauzima:', train_images.nbytes, "bajta u memoriji."])
print("")


#### test set
print('-- Test set')
print('')
print(*['Oblik seta podataka test_images je formata (n, px, px):', test_images.shape])
print('Prva vrijednost predstavlja broj slika u skupu, dok druga i treca vrijednost predstavljaju rezoluciju.')
print('')

## test labels

print(*['Velicina skupa test_labels:', len(test_labels)])
print('Sami prikaz test_labels skupa (pogledati threshold comment):')
print(test_labels)
print("")

## info - test_images

print(*['Element test_images type:', test_images.dtype])
print(*['Svaki element np niza kojim su kodirane slike zauzima:', test_images.itemsize, "byte"])
print(*['Citav skup u memoriji zauzima:', test_images.nbytes, "bajta u memoriji."])
print("")

-- Train set

Oblik seta podataka train_images je formata (n, px, px): (60000, 28, 28)
Prva vrijednost predstavlja broj slika u skupu, dok druga i treca vrijednost predstavljaju rezoluciju.

Velicina skupa train_labels: 60000
Sami prikaz train_labels skupa (pogledati threshold comment):
[5 0 4 ... 5 6 8]

Element train_images type: uint8
Svaki element np niza kojim su kodirane slike zauzima: 1 byte
Citav skup u memoriji zauzima: 47040000 bajta u memoriji.

-- Test set

Oblik seta podataka test_images je formata (n, px, px): (10000, 28, 28)
Prva vrijednost predstavlja broj slika u skupu, dok druga i treca vrijednost predstavljaju rezoluciju.

Velicina skupa test_labels: 10000
Sami prikaz test_labels skupa (pogledati threshold comment):
[7 2 1 ... 4 5 6]

Element test_images type: uint8
Svaki element np niza kojim su kodirane slike zauzima: 1 byte
Citav skup u memoriji zauzima: 7840000 bajta u memoriji.



#### 3.1.1 Koliko slika ima u skupu za treniranje?

- U skupu za trenitranje se nalazi 60000 slika.

#### 3.1.2 Koja je rezolucija slika?

- Slike su predstavljene kao np (numpy) niz, poziv nad `.shape` naredbom daje nam broj slika i informacije o samim slikama. Rezolucija slika je 28x28 pixela. 

#### 3.1.3 Kojeg tipa su osnovne informacije unutar slika? i koliko bita zauzimaju u memoriji?

- Osnovnu informaciju o slikama mozemo saznati pomocu `.dtype` naredbe. A to jeste da je `uint8` tip podataka.
- Broj bita koje slike zauzimaju u memorije mozemo saznati pomocu `.itemsize` naredbe. Svaki element u nizu zauzima 1 `byte` odnosno 8 bita.


#### 3.1.4 Koliko prostora ce citav skup zauzeti u memoriji?

- Ovo mozemo saznati pomocu naredbe `.nbytes`. U nasem slucaju za za train set to iznosi 47040000 `byte`-a.

#### 3.1.5 Odgovorite na ista pitanja za testni skup podataka.

- U `test_images` skupu podataka se nalazi 10000 slika. 
- Rezolucija slika u  je 28x28 pixela.
- Osnovne informacije unutar slika su također tipa `uint8`, i sto kao testni skup u memoriji zauzimaju 1 `byte` odnosno 8 bita.
- Čitav skup testnih podataka u memoriji zauzima 7840000 `byte`-a. 

### 3.2 Definisanje neuronske mreze

In [58]:
from keras import models
from keras import layers
from keras.utils import to_categorical

network = models.Sequential()

network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape = (28 * 28,)))
network.add(layers.Dense(10, activation = 'softmax'))

network.compile(optimizer = 'rmsprop', loss = 'categorical_crossentropy', metrics = ['accuracy'])

## preprocessing

print("-- Train slike")
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255

print(*['Tip podataka nakon pretvaranja:', train_images.dtype, 'i broj bita elemenata, nakon pretvaranja:',
        train_images.itemsize, 'bytes'])
print('Vrijednosti: ')
print(train_images)
print('')

print("-- Test slike")

test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

print(*['Tip podataka nakon pretvaranja:', test_images.dtype, 'i broj bita elemenata nakon pretvaranja:',
        test_images.itemsize, 'bytes'])
print('Vrijednosti: ')
print(test_images)
print('')

## labele

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)



-- Train slike
Tip podataka nakon pretvaranja: float32 i broj bita elemenata, nakon pretvaranja: 4 bytes
Vrijednosti: 
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

-- Test slike
Tip podataka nakon pretvaranja: float32 i broj bita elemenata nakon pretvaranja: 4 bytes
Vrijednosti: 
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]



#### 3.2.1 Sta radi naredba reshape? A sta astype?

- Naredba `reshape` mijenja sam niz i strukturu unutar njega. Prvi parametar predstavlja koliko nizova se zeli unutar vec postojeceg niza, dok drugi parametar predstavlja broj elemenata u tim istim nizovima unutar niza.
- Naredba `astype` pretvara podatke u niz iz početnog tipa u navedeni tip podataka. U ovom slučaju, podaci su pretvoreni u tip `float32`.

#### 3.2.2 Koje vrijednosti su sada snimljene u `train_images` i `test_images`?

- Sada imamo spremljene `float` vrijdnosti koje se nalaze u segmentu od [0, 1].

#### 3.2.3 Koliko bita sada zauzima jedan pixel u memoriji?

- Jedan podatak sada zauzima 4 `byte`-a odnosno 32 bita, jer je `float32` u pitanju.

### 3.3 Treniranje mreze

In [59]:
network.fit(train_images, train_labels, epochs = 5, batch_size = 128)

train_loss, train_acc = network.evaluate(train_images, train_labels)
print('')
print(*['Vrijednost tacnosti - train set:', train_acc])
print(*['Vrijednost funkcije gubitka - train set:', train_loss])

Epoch 1/5
469/469 [==============================] - 1s 2ms/step - loss: 0.2561 - accuracy: 0.9266
Epoch 2/5
469/469 [==============================] - 1s 2ms/step - loss: 0.1043 - accuracy: 0.9692
Epoch 3/5
469/469 [==============================] - 1s 2ms/step - loss: 0.0689 - accuracy: 0.9793
Epoch 4/5
469/469 [==============================] - 1s 2ms/step - loss: 0.0504 - accuracy: 0.9849
Epoch 5/5
1875/1875 [==============================] - 1s 533us/step - loss: 0.0259 - accuracy: 0.9929

Vrijednost tacnosti - train set: 0.9928833246231079
Vrijednost funkcije gubitka - train set: 0.025942832231521606


#### 3.3.1 Sta je epoha?

- Epoha predstavlja broj kompletnih/full prolazaka kroz čitav skup podataka. Moze biti 1 ili n batcheva.

#### 3.3.2 Šta određuje parametar `batch_size` ?

- Parametar `batch_size` odreduje broj uzoraka koji se koristi/procesira prije ažuriranja modela i njegovih internih stanja. 

#### 3.3.3 Koje vrijednosti vidite u konzoli u toku procesa treniranja?

- Epoha koja je aktivna (Epoch 1/5 npr)
- Vrijednost `batch_size` varijable (ispod epohe i desno od velicine skupa)
- Velicina skupa koji se trenira (desno od varijable batch-a)
- ETA: Estimated time of arrival, tj. vrijeme za koje ce se zavrsiti epoha
- Preciznost (accuracy)
- Vrijednost funkcije gubitka (loss)

#### 3.3.4 Koja je tacnost i vrijednost funkcije gubitka? 

In [60]:
print(*['Tacnost:', train_acc])
print(*['Vrijednost funkcije gubitka:', train_loss])

Tacnost: 0.9928833246231079
Vrijednost funkcije gubitka: 0.025942832231521606


### 3.4 Evaluacija mreze

In [61]:
test_loss, test_acc = network.evaluate(test_images, test_labels)

print('')
print(*['Vrijednost tacnosti - test set:', test_acc])
print(*['Vrijednost funkcije gubitka - test set:', test_loss])

313/313 [==============================] - 0s 862us/step - loss: 0.0651 - accuracy: 0.9804

Vrijednost tacnosti - test set: 0.980400025844574
Vrijednost funkcije gubitka - test set: 0.0650714710354805


#### 3.4.1 Koja je tacnost i vrijednost funkcije gubitka u skupu testnih podataka? 

In [62]:
print(*['Tacnost:', test_acc])
print(*['Vrijednost funkcije gubitka:', test_loss])

Tacnost: 0.980400025844574
Vrijednost funkcije gubitka: 0.0650714710354805


## 4. Samostalni zadatak

- Izvrseno je slikanje i fragmentiranje, kao sto je navedeno u postavci, te je u nastavku provjeren nas model u odnosu na novonastale slike.
- Svaka slika u svom imenu sadrzi sljedeci pattern: `indikatorBroja_indexBrojaKrecuciOd1.png`.
- Npr: `4_2.png` znaci da je to broj `4`, a da je to druga slika u nasem datasetu.
- Slika koja sadrzi sve brojeve je uploadovana na `imgur` i u slucaju problema sa prikazom, mogu naknadno poslati istu.
- Slike su obradjene unaprijed sa formatom `28x28`.
- Slika koja sadrze sve slike je data u nastavku:

![brojevi.png](https://i.imgur.com/WuGdQYx.png)

In [63]:
import numpy as np
import glob
import re

from keras.utils import to_categorical
from PIL import Image, ImageOps

def loadImagesFromSlibeLocalFolder():
    images = np.zeros((30,28,28), order = 'C', dtype = np.uint8)
    directoryImages = glob.glob('./slibe/*.png')

    labels = np.array([0,0,0,1,1,1,2,2,2,3,3,3,4,4,4,5,5,5,6,6,6,7,7,7,8,8,8,9,9,9])
    
    for imagePath in directoryImages:
        new_image = Image.open(imagePath).convert('L')

        numbers = re.findall("\d+", imagePath)
        number_digit = int(numbers[0])
        number_index = int(numbers[1]) - 1
        
        final_index = number_digit * 3 + number_index
        # invertovanje boja
        images[final_index] = ImageOps.invert(new_image)
        
    return images, labels
    
    
images, labels = loadImagesFromSlibeLocalFolder()

images = images.reshape((30, 28*28))
images = images.astype('float32') / 255
labels = to_categorical(labels)

rd_loss, rd_acc = network.evaluate(images, labels)

print('')
print(*['Vrijednost tacnosti:', rd_acc])
print(*['Vrijednost funkcije gubitka:', rd_loss])

1/1 [==============================] - 0s 939us/step - loss: 27.9590 - accuracy: 0.1000

Vrijednost tacnosti: 0.10000000149011612
Vrijednost funkcije gubitka: 27.958982467651367


#### 4.1 Koja je tacnost i vrijednost funkcije gubitka? 


In [64]:
print(*['Tacnost:', rd_acc])
print(*['Vrijednost funkcije gubitka:', rd_loss])

Tacnost: 0.10000000149011612
Vrijednost funkcije gubitka: 27.958982467651367


### Komentar, zapazanja

- Ako poredimo pocetni dataset (online prikaz) i slike postavljene, vidimo da u pocetnom datasetu je crno-bijela varijanta vecinski zastupljena, samim tim se pozadina drasticno razlikuje od kontura. Na slikama postavljenim sa moje strane je mala razlika background-a u odnosu na konture (sto se moze primijetiti ispisom i gledajuci u vrijednosti), shodno time nije ocekivana velika tacnost prilikom treniranja sa 5 epoha.
- Probao sam isto sa 2 i 3 epohe, i dobio sam bolji rezultat, tj. u slucaju veceg offseta za gresku, daje bolju detekciju u odnosu na postavljene slike.